### ISSUE TITLE
Implement OAuth2

### ISSUE THREAD

**Issue by andybeletsky** [lbryio/odysee-api#225]

**Comment by superkruger** [comment]
If I were to contribute with this, did you have an OAuth2 provider or client implementation in mind?

**Comment by andybeletsky** [comment]
Thank you for your interest @superkruger, unfortunately our provider side for this is not ready and most likely won't be for a few more weeks.

**Comment by superkruger** [comment]
Gotcha.
I could help with the provider side too...
