### ISSUE TITLE
drop lbry from this repo name (rename to odysee-sdks or web-sdks)

### ISSUE THREAD

**Issue by kauffj** [lbryio/odysee-api#311]
we should also begin moving endpoints to api.odysee.com

**Comment by kauffj** [comment]
this isn't a priority, but given that it's now a given lbrytv is over, it would be good to rename this repo and move the endpoint domain

initial move of the endpoint domain be done in way that allows both to continue working

**Comment by kauffj** [comment]
@andybeletsky can this happen soon?

**Comment by andybeletsky** [comment]
It is done.
