### ISSUE TITLE
Custom Grossness Tags / Flags system ( Idea ) 

### ISSUE THREAD

**Issue by JYamihud** [lbryio/odysee-api#323]
In my post [Should "Content" be Free?](https://odysee.com/@blenderdumbass:f/Should-Content-be-Free:b) I explored some ideas relating the current `mature` tag on the LBRY. And I think it needs a strong enhancement. 

# The problem with Mature

Mature or not, it's not enough information about a given publication in order to decide whether I want to see it or want to avoid it. A lot of people will not have a problem with pornography but will have a problem with videos where people eat poo. But both types of videos will be flagged as `mature` in the current system.

# Proposal

Add a system similar to tags but done while flagging. So people could flag a video as `porn` or `poo` or `death` or what ever else. Make the system expendable. So people could add their own flags. 

Those publications will not load even thumbnails for people who didn't allow a given flag. So by any chance not to get traumatic instances while looking at a thumbnail. *I can get pretty traumatic seeing a frame from a hunting scene from The House That Jack Built*

People who look for a publication flagged with a flag that's not yet allowed for this person. They will see that the publication exists. Maybe the title would be not too bad. And there will be a warning. And a button to allow those flags to show. 

Maybe some menu like allow ones, allow forever and allow all flags could exist. Also subscribing to flags could also be a thing. Since they are probably going to be tags but reddish like the `mature` tag.

# Reference

There is a similar system already implemented on IMDB. On each film page you can find a "Parental Guide" with all the gross scenes from a given movie. I don't have this for videos yet. And it's not very comforting.

**Comment by JYamihud** [comment]
# PUBLISHED ON ODYSEE [HERE](https://odysee.com/@blenderdumbass:f/New-Flagging-System:c)

Not so long ago I written an [article](https://odysee.com/@blenderdumbass:f/Should-Content-be-Free:b) about whether "Content Freedom" should be a thing. Whether people should have an ability to upload anything they want. I concluded with that... Yes. But only with a sufficient enough warning system. Like a thing that warns you about what type of publication you are about to see, is present.

I want to dedicate this article to propose that kind of system. I already opened an [issue](https://github.com/lbryio/lbrytv/issues/323) on LBRY's git repository. Tho it's a bit broader than this article. I had thought about some things. And I have a few interesting ideas.

# Flags now

Current implementation of a flag system on Odysee ( and probably the rest of LBRY applications) at the moment works like this.

![](https://cdn.lbryplayer.xyz/api/v4/streams/free/flag-system-01/e662077de474e55abceec0ba2cc572517a183bf3/26edf7)

You click the flag button and you get this menu. You can choose what kind of stuff you personally didn't like. And behind the scenes it will do one of two things. In FAQ about ["content"](https://lbry.com/faq/content) they avoid the issue of the `mature`. And talk about mainly the DMCA stuff. That they touch on even more [here](https://lbry.com/faq/dmca).

The first thing that can happen. Is that if a DMCA request happens. The url of the publication will be added into [this](https://github.com/lbryio/dmca) repository. And the LBRY developed software and websites will not show a publication if it's on this list. It's still on the LBRY protocol. It's not going to be removed. But you will need to modify your software to see it. So fork the LBRY Desktop please.

I think this is going to be done to illegal publications in the US where the company is. So anything where copyright is an issue and there is a DMCA request. And Child Porn will be removed.

For the rest of the publications it will probably add a `mature` tag on them. But I'm not sure. Because I couldn't find information about it. And I'm not willing to flag somebody just to check it out. If you know please comment about it.

# Issues with that

Let's say that Lars Von Trier finds out about LBRY and wants to upload him movie, The House That Jack Built, to it. I gonna mention it again. I know, if you read my previous publications. I talk about this one a lot. But it's just a very good example.

If he uploads it him self. There is no problem of DMCA. Because he probably holds the copyright (The company that distributes the film is his). There is no illegal pornography in the movie. Even tho it could look like there is. Pictures of Murder of children are not illegal. Only sexual child images are illegal. So the movie is not removed with DMCA. And not removed because it's legal. Then what? Probably it will be under a `mature` tag.

I don't have a problem with tits. I enabled `mature` in the LBRY desktop. But I don't want child death scenes. What could be done?

# Proposal 0.1

The first idea was to extend the `mature` tag to enable other tags like `child-death` or simple `death` to appear in the network. Making the choice of publication a bit more versatile. This has a limitation tho. If you make any number of tags that are strict. With the current system is 1 tag. If you add `death` it will be 2 tags. If there are 2 hard coded tags. It's not very helpful for people who are afraid or want to avoid other things.

What if there are only 10 people in the world who afraid from Cute Cat videos. And one would be brave enough to flag a video with cute cats in them. So the other 9 could avoid that video. `cute-cat` is not the type of tag that a reasonable developer would think about when designing a system like this. Should we just disregard this as not important? Or do we have a deeper system at our hands?

Another issue that I want you to think about. Is what will happen if people could tag things them selves. For publications that is not theirs. There could be a lot of trolls and malicious people that would abuse that system. How do we deal with it?

# What do I keep in mind when I design?

In order to solve those issues. I want to talk about what to I think about when designing the system. And how I want to approach it. If this article will be seen by the developers and will be implemented. What were my motivations? So it's not going to go out of vision.

**I am trying to insure maximum Freedom.** And this kind of system would make sure both, that people can upload anything they want. And that people could avoid anything they don't want to see. It's their choice to avoid something or not.

It's not supposed to be a policing thing. It's not supposed to be something that makes the protocol this place where if I hate your opinion I will click the Flag button and add `hate` to the list of tags. I want it to be resistant to such nonsense. Even if it's allowed. 

# Proposal 0.2

![](https://cdn.lbryplayer.xyz/api/v4/streams/free/flag-system-02/54c3fc8b0bd47b6715ec038a1157df033ef61785/3664ca)

So you come into Odysee and you type "cute cats" in the search. You get one publication that somebody flagged as `cute-cats` that so happened to be still not allowed by you. You can either click on the red tag. And choose allow. Or avoid the publication. If it's something you rather avoid.

If you accidentally click on the publication it would not play. You will see a big warning sign instead of the video player. And a list of flags on that publication.

I think a menu of options could be there both when you click on each individual flag. And for all flags together:

 - **Allow**. Adding the flag to a whitelist of a kind. Making it ignore the warning of this particular flag in future. Similar to allowing `mature` in the current system.
 - **Allow Ones**. Maybe you want to see this just now. But keep avoiding later.
 - **Allow for X amount of time**. To be able to test yourself. You could choose a time while this flag will be visible for you. And then automatically blocked again.
 - **Censor**. Make it so you never even see publications with this flag. Like if they don't exist in the platform. But obviously just for you.

This solves it a little bit. For example if abuser wants to add some flags to it when they are not harmful or that are misleading. You will still be able to find the publication. And with a click of a button still see it.

But it makes spamming flags be a thing. So how do we deal with it?

# Proposal 0.3

LBC is a very good thing. It's just an essential part of LBRY protocol that I think we can use it for this system. When you flag somebody it's like making a little publication. If you have little LBC it's fine. The publication will take like 0.001 LBC. And you successfully flagged something.

Every other person may flag it again. Or support your flag with his own LBCs. Making some flags more noteworthy than the others.

In the setting apart from just having a simple white list. You can also have a setting of reason-ability. Basically you choose how much LBC should be on a flag before your account considers it worthy of blocking.

We should make it a separate thing from simple publication. Because it should not give a monetary incentive to flag anybody. People would abuse the system making weird flags. So then if somebody supports the flag they could unlock the tip and run with it.

Also flagging or supporting flags should be limited in LBC. Let's say up to 5 LBC. Why? Because people with money could use it to put a very highly payed flag to a publication they hate. It should be multiple accounts supporting one flag together in order for it to be noteworthy.

There is no conclusion is this post. I don't want to conclude it yet. This proposal worth trying, but I think you will figure out why I'm wrong on so many things. This is a gift of freedom of speech. I propose an idea. You criticise it. We both improve the idea.

I want to read what you have to say about it. Please comment. And **Happy Hacking**.

*This post is under CC-BY-SA.*

# PUBLISHED ON ODYSEE [HERE](https://odysee.com/@blenderdumbass:f/New-Flagging-System:c)

**Comment by kauffj** [comment]
@JYamihud want a job?

**Comment by JYamihud** [comment]
@kauffj Having a job will make me potentially fire-able. You can't fire a volunteer. And also. I need to loose weight. Las time I had a job I ate too much. So I'm willing to help in any way shape or form. But only if you don't pay me in a formal way. LBC support. I don't mind.

**Comment by kauffj** [comment]
@JYamihud haha, well it will be quite a bit of work to build all of this :)

But it's very much aligned with our current thoughts and we could use all the help we can get. Can you email me at jeremy@lbry.com to discuss further?
