### ISSUE TITLE
Support transcode on upload feature, at least for some files that are incompatible 

### ISSUE THREAD

**Issue by tzarebczan** [lbryio/odysee-api#336]
On the app side, we can detect if a file is not in the proper format and may need transcoding. For now, we can warn users, but in the future we can do the same on the backend and queue these files up for transcoding. 

Would need to put together a list of popular non-supported codecs that are used, as opposed to an allow list.

**Comment by andybeletsky** [comment]
Do we want to just downcode it to some digestible bitrate?

**Comment by tzarebczan** [comment]
We can also do that for files over 5mbps. The main goal was to make the videos compatible with all browsers.
