### ISSUE TITLE
Collect better playback metrics from clients

### ISSUE THREAD

**Issue by andybeletsky** [lbryio/odysee-api#350]
We need to collect playback time as well as buffering events duration, among other things.

[Watchman API spec](https://github.com/lbryio/odysee-api/blob/watchman/apps/watchman/gen/http/openapi.yaml)

**Comment by andybeletsky** [comment]
[Frontend part](https://github.com/lbryio/lbry-desktop/issues/6437)

**Comment by DispatchCommit** [comment]
discussion recap:
`cache` doesn't have a clear / distinct value for HLS streams (m3u8 could be cached, segment files might not be for instance)
Rename `format` to `protocol` - better descriptor of data
Rename `rate` to `bandwidth` - rate is ambiguous, could refer to video playback rate, or viewer download rate for instance.

Will use existing schema definitions for now though

**Comment by andybeletsky** [comment]
Fields have been renamed.

**Comment by tzarebczan** [comment]
Are we still going to be using the other endpoint to track time to start? Or should that be brought in here with an initial call on playback start?

**Comment by andybeletsky** [comment]
We'll probably combine it but I want to address one thing at a time.
