### ISSUE TITLE
Just change the default web title to Odysee

### ISSUE THREAD

**Issue by AnantGupta384** [lbryio/odysee-api#359]
The default title on the web based client it **odysee.com** to **Odysee**. Just a non emergency issue. Keep up the great work.
![image](https://user-images.githubusercontent.com/71361442/129545021-4b5448b7-6859-41b1-b531-d7f6c7afd02b.png)

**Comment by tzarebczan** [comment]
Issue moved to [lbryio/lbry-desktop #6994](https://github.com/lbryio/lbry-desktop/issues/6994) via [**ZenHub**](https://www.zenhub.com/)
