### ISSUE TITLE
Consider separating file uploads from publish call

### ISSUE THREAD

**Issue by kauffj** [lbryio/odysee-api#92]
Coupling the `publish` call with metadata with the file upload raises two issues:

- It means a file upload cannot begin until all metadata is provided
- It changes the typical signature of API calls to require multipart posts

Instead, the design could be a two part process:

- A file upload endpoint that receives files from authenticated users and returns a unique file token.
- A publish endpoint that takes a file token in the place of the `file_path` parameter

**Comment by andybeletsky** [comment]
This will be addressed in #202
